service: hkha-aed-wait-watch

frameworkVersion: ">=1.61.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7

functions:
  cron:
    handler: handler.run
    events:
      - schedule: cron(2,17,32,47 * * * ? *)
